-- CAP CAUCASO --
local DTgeneral = SET_GROUP:New()
DTgeneral:FilterPrefixes({"BS EWR", "RS AWACS"})
DTgeneral:FilterStart()
Detection = DETECTION_AREAS:New(DTgeneral, 30000)
local DetectionSetGroup1 = SET_GROUP:New()
DetectionSetGroup1:FilterPrefixes({"RED1 EWR"})
DetectionSetGroup1:FilterStart()
Detection1 = DETECTION_AREAS:New(DetectionSetGroup1, 30000)
local DetectionSetGroup2 = SET_GROUP:New()
DetectionSetGroup2:FilterPrefixes({"RED2 EWR"})
DetectionSetGroup2:FilterStart()
Detection2 = DETECTION_AREAS:New(DetectionSetGroup2, 30000)

CAPDispatcher = AI_A2A_DISPATCHER:New(Detection)
RA1ADispatcher = AI_A2A_DISPATCHER:New(Detection1)
RA2ADispatcher = AI_A2A_DISPATCHER:New(Detection2)

--[[ CAPDispatcher:SetTacticalDisplay(true)
RA1ADispatcher:SetTacticalDisplay(true)
RA2ADispatcher:SetTacticalDisplay(true) ]]
-- GENERAL
Beslan_base = ZONE_AIRBASE:New(AIRBASE.Caucasus.Beslan, 100000)
FrontGRAL1 = ZONE_POLYGON:New("FrontGRAL1", GROUP:FindByName("BORDER_general1"))
FrontGRAL2 = ZONE_POLYGON:New("FrontGRAL2", GROUP:FindByName("BORDER_general2"))
CAPDispatcher:SetSquadron("CAP_general", AIRBASE.Caucasus.Beslan, "CAP_general_29A")
CAPDispatcher:SetSquadronOverhead("CAP_general", 1)
CAPDispatcher:SetSquadronCap("CAP_general", FrontGRAL1, 4000, 8000, 600, 800, 800, 1200, "BARO")
CAPDispatcher:SetSquadronCapInterval("CAP_general", 1, 30, 120, 1)
CAPDispatcher:SetSquadronGci("CAP_general", 900, 1200)
CAPDispatcher:SetSquadronTakeoffInAir("CAP_general")
CAPDispatcher:SetDefaultGrouping(2)
CAPDispatcher:SetDefaultLandingAtRunway()
CAPDispatcher:SetBorderZone({FrontGRAL1, FrontGRAL2})
-- BATUMI
Batumi_base = ZONE_AIRBASE:New(AIRBASE.Caucasus.Batumi, 20000)
Frontroja1 = ZONE_POLYGON:New("Frontroja1", GROUP:FindByName("BORDER_BATUMI"))
RA1ADispatcher:SetSquadron("Batumi_defend", AIRBASE.Caucasus.Batumi, "BATUMI_MISSION_AIR", 10)
RA1ADispatcher:SetSquadronOverhead("Batumi_defend", 1.5)
RA1ADispatcher:SetSquadronCap("Batumi_defend", Batumi_base, 600, 1500, 400, 600, 575, 700, "BARO")
RA1ADispatcher:SetSquadronCapInterval("Batumi_defend", 1, 30, 60, 1)
RA1ADispatcher:SetSquadronGci("Batumi_defend", 900, 1200)
RA1ADispatcher:SetSquadronTakeoffFromParkingCold("Batumi_defend")
RA1ADispatcher:SetDefaultGrouping(2)
RA1ADispatcher:SetDefaultLandingAtRunway()
RA1ADispatcher:SetBorderZone(Frontroja1)
-- SUJUMI
Sujumi_base = ZONE_AIRBASE:New(AIRBASE.Caucasus.Sukhumi_Babushara, 20000)
Frontroja2 = ZONE_POLYGON:New("Frontroja2", GROUP:FindByName("BORDER_SUJUMI"))
RA2ADispatcher:SetSquadron("Sujumi_defend", AIRBASE.Caucasus.Sukhumi_Babushara, "SUJUMI_MISSION_AIR", 14)
RA2ADispatcher:SetSquadronOverhead("Sujumi_defend", 1.5)
RA2ADispatcher:SetSquadronCap("Sujumi_defend", Sujumi_base, 1000, 3000, 400, 600, 575, 700, "BARO")
RA2ADispatcher:SetSquadronCapInterval("Sujumi_defend", 1, 30, 60, 1)
RA2ADispatcher:SetSquadronGci("Sujumi_defend", 900, 1200)
RA2ADispatcher:SetSquadronTakeoffFromParkingCold("Sujumi_defend")
RA2ADispatcher:SetDefaultGrouping(2)
RA2ADispatcher:SetDefaultLandingAtRunway()
RA2ADispatcher:SetBorderZone(Frontroja2)
