-- script CAP --
_SETTINGS:SetPlayerMenuOff()

local DTlibano = SET_GROUP:New()
DTlibano:FilterPrefixes({"LBNEWR"})
DTlibano:FilterStart()
Detection_LBN = DETECTION_AREAS:New(DTlibano, 30000)

local DTsyria = SET_GROUP:New()
DTsyria:FilterPrefixes({"SYRIAEWR", "RS AWACS"})
DTsyria:FilterStart()
Detection_Syria = DETECTION_AREAS:New(DTsyria, 30000)

-- GENERAL
DamascoDispatcher = AI_A2A_DISPATCHER:New(Detection_Syria)
-- DamascoDispatcher:SetTacticalDisplay(true)
local Damasco_base = ZONE_AIRBASE:New(AIRBASE.Syria.Damascus, 10000)
local FrontSYRIA = ZONE_POLYGON:New("FrontSYRIA", GROUP:FindByName("BORDER_SYRIA"))
DamascoDispatcher:SetDefaultGrouping(2)
DamascoDispatcher:SetSquadron("CAP_Patrol_Damasco", AIRBASE.Syria.Damascus, "SYRIAM29C")
DamascoDispatcher:SetSquadronTakeoffInAir("CAP_Patrol_Damasco")
DamascoDispatcher:SetSquadronCap("CAP_Patrol_Damasco", Damasco_base, 4000, 8000, 600, 800, 800, 1200, "BARO")
DamascoDispatcher:SetSquadronCapInterval("CAP_Patrol_Damasco", 1, 180, 600)
DamascoDispatcher:SetSquadronOverhead("CAP_Patrol_Damasco", 1)
DamascoDispatcher:SetSquadronGci("CAP_Patrol_Damasco", 900, 1200)
DamascoDispatcher:SetDefaultLandingAtRunway()
DamascoDispatcher:SetBorderZone({FrontSYRIA})

LBNDispatcher = AI_A2A_DISPATCHER:New(Detection_LBN)
-- LBNDispatcher:SetTacticalDisplay(true)
local Beirut_base = ZONE_AIRBASE:New(AIRBASE.Syria.Beirut_Rafic_Hariri, 10000)
local FrontLBN = ZONE_POLYGON:New("FrontLBN", GROUP:FindByName("BORDER_LIBANO"))
LBNDispatcher:SetDefaultGrouping(2)
LBNDispatcher:SetSquadron("LBN_CGI", AIRBASE.Syria.Mezzeh, "LBN29A" )
LBNDispatcher:SetSquadronTakeoffInAir("LBN_CGI")
LBNDispatcher:SetSquadronCap("LBN_CGI", Beirut_base, 4000, 8000, 600, 800, 800, 1200, "BARO")
LBNDispatcher:SetSquadronCapInterval("LBN_CGI", 1, 180, 600)
LBNDispatcher:SetSquadronGci("LBN_CGI", 900, 1200)
LBNDispatcher:SetSquadronOverhead("LBN_CGI", 1)
LBNDispatcher:SetDefaultLandingAtRunway()
LBNDispatcher:SetBorderZone({FrontLBN})
